<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-I097JJ7B" failures="1" tests="8" name="FirefoxTest" time="17.82" errors="0" timestamp="2023-07-14T14:18:04 CEST">
  <testcase classname="testClasses.Test1" name="step2" time="0.912"/>
  <testcase classname="testClasses.Test1" name="step3" time="0.754"/>
  <testcase classname="testClasses.Test1" name="step4" time="0.255"/>
  <testcase classname="testClasses.Test1" name="step5" time="0.694"/>
  <testcase classname="testClasses.Test1" name="step6" time="0.106"/>
  <testcase classname="testClasses.Test1" name="step7" time="0.407">
    <failure type="java.lang.AssertionError" message="expected [https://qualityminds.com/services/core-qa-services/test-automation/] but found [https://qualityminds.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://qualityminds.com/services/core-qa-services/test-automation/] but found [https://qualityminds.com/]
at testClasses.Test1.step7(Test1.java:99)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- step7 -->
  <testcase classname="testClasses.Test1" name="step8" time="0.004">
    <skipped/>
  </testcase> <!-- step8 -->
  <testcase classname="testClasses.Test1" name="step9" time="0.0">
    <skipped/>
  </testcase> <!-- step9 -->
</testsuite> <!-- FirefoxTest -->
